name: "Generate Release for Deno with Conventional Commit"
description: "Generates a release for a Deno project based on conventional commits"
author: "David Overcash"

branding:
  icon: "check"
  color: "green"

inputs:
  GITHUB_TOKEN:
    description: "A github token with write access to the repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Configure Git
      shell: bash
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Generate Release
      shell: bash
      run: deno run --allow-all ${{ github.action_path }}/generate-release.ts
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
